/**
 * Option 规范化工具函数
 *
 * 注意：统一将单个对象转换为数组格式，支持未来多 grid/axis 扩展
 */

import type { AxisOption, ChartOption, XAxisOption, YAxisOption, GridOption, VisualMapOption } from "@/types"

/**
 * 规范化网格配置：统一转换为数组
 */
export function normalizeGrid(grid?: GridOption | GridOption[]): GridOption[] {
  if (!grid) return []
  return Array.isArray(grid) ? grid : [grid]
}

/**
 * 规范化 X 轴配置：统一转换为数组
 */
export function normalizeXAxis(axis?: XAxisOption | XAxisOption[]): XAxisOption[] {
  if (!axis) return []
  return Array.isArray(axis) ? axis : [axis]
}

/**
 * 规范化 Y 轴配置：统一转换为数组
 */
export function normalizeYAxis(axis?: YAxisOption | YAxisOption[]): YAxisOption[] {
  if (!axis) return []
  return Array.isArray(axis) ? axis : [axis]
}

/**
 * 规范化轴配置：将单个对象或数组统一转换为数组（向后兼容）
 */
export function normalizeAxis(axis: AxisOption | AxisOption[] | undefined): AxisOption[] {
  if (!axis) {
    return []
  }
  return Array.isArray(axis) ? axis : [axis]
}

/**
 * 规范化 VisualMap 配置：统一转换为数组
 */
export function normalizeVisualMap(visualMap?: VisualMapOption | VisualMapOption[]): VisualMapOption[] {
  if (!visualMap) return []
  return Array.isArray(visualMap) ? visualMap : [visualMap]
}

/**
 * 从 series 配置自动生成 visualMap
 *
 * 智能默认值功能：
 * - 检测 series 中的 colorMap 和 valueRange 配置
 * - 自动生成对应的 visualMap 配置
 * - 用户显式配置的 visualMap 优先级更高
 *
 * @param series - 系列配置数组
 * @param existingVisualMap - 用户显式配置的 visualMap
 * @returns 合并后的 visualMap 配置数组
 */
export function generateVisualMapFromSeries(
  series: any[],
  existingVisualMap: VisualMapOption[]
): VisualMapOption[] {
  const autoGeneratedMaps: VisualMapOption[] = []

  // 遍历 series，检测需要自动生成 visualMap 的情况
  series.forEach((s, index) => {
    // 只处理瀑布图类型
    if (s.type !== 'waterfall') return

    // 检查是否有 colorMap 和 valueRange 配置
    if (!s.colorMap || !s.valueRange) return

    // 跳过 'auto' 类型的 valueRange（需要实际数据才能确定范围）
    if (s.valueRange === 'auto') return

    // 检查是否已经有显式配置的 visualMap 关联到此 series
    const hasExplicitVisualMap = existingVisualMap.some(vm => {
      if (vm.seriesIndex === undefined) return false
      const indices = Array.isArray(vm.seriesIndex) ? vm.seriesIndex : [vm.seriesIndex]
      return indices.includes(index)
    })

    // 如果已有显式配置，跳过自动生成
    if (hasExplicitVisualMap) return

    // 获取 series 对应的 gridIndex
    const gridIndex = s.yAxisIndex ?? 0

    // 根据 gridIndex 计算 top 位置
    // 假设有 2 个 grid：grid[0] 在上半部分，grid[1] 在下半部分
    // 这里使用简单的策略：根据 gridIndex 计算百分比位置
    let topPosition: string | number = 'center'

    // 如果有多个 grid，根据 gridIndex 调整位置
    if (gridIndex === 0) {
      topPosition = '25%'  // 上半部分的中心
    } else if (gridIndex === 1) {
      topPosition = '75%'  // 下半部分的中心
    }

    // 自动生成 visualMap 配置
    const autoVisualMap: VisualMapOption = {
      show: true,
      type: 'continuous',
      min: s.valueRange[0],
      max: s.valueRange[1],
      colorMap: s.colorMap,
      seriesIndex: index,
      orient: 'vertical',
      right: 20,
      top: topPosition,
      itemWidth: 20,
      itemHeight: 200,
      splitNumber: 5,
      textStyle: {
        color: '#ccc',
        fontSize: 10
      },
      unit: {
        show: true,
        text: 'dB',
        color: '#ccc',
        fontSize: 10
      }
    }

    autoGeneratedMaps.push(autoVisualMap)
  })

  // 合并：用户显式配置 + 自动生成
  // 用户配置在前，优先级更高
  return [...existingVisualMap, ...autoGeneratedMaps]
}

/**
 * 规范化完整的 ChartOption
 *
 * 将所有配置统一转换为数组格式
 * 智能生成 visualMap（如果 series 中有 colorMap 配置）
 */
export function normalizeChartOption(option: any): ChartOption {
  // 先规范化基础配置
  const normalizedSeries = option.series?.filter((s: any) => s !== undefined) ?? []
  const normalizedVisualMap = normalizeVisualMap(option.visualMap)

  // 智能生成 visualMap
  const finalVisualMap = generateVisualMapFromSeries(normalizedSeries, normalizedVisualMap)

  return {
    ...option,
    grid: normalizeGrid(option.grid),
    xAxis: normalizeXAxis(option.xAxis),
    yAxis: normalizeYAxis(option.yAxis),
    visualMap: finalVisualMap,
    series: normalizedSeries
  }
}
